{% set name = "mongoengine" %}
{% set version = "0.22.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "9f66c08e2b045bf23a2ca26813a510ec3beb6253f631779f9110555fd8f5a283" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pymongo >=2.7.1
    - six

test:
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: MongoEngine is a Python Object-Document Mapper for working with MongoDB.
  doc_url: https://mongoengine-odm.readthedocs.io/
  dev_url: https://github.com/MongoEngine/mongoengine

extra:
  recipe-maintainers:
    - pmlandwehr
    - dgasmith
    - lnaden
