{% set name = "mongoengine" %}
{% set version = "0.22.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "620d13db551c849402eb3c362878934f5260ec0028fff2a5d81bf53b21d91572" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - pymongo >=2.7.1
    - six

test:
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: MongoEngine is a Python Object-Document Mapper for working with MongoDB.
  doc_url: https://mongoengine-odm.readthedocs.io/
  dev_url: https://github.com/MongoEngine/mongoengine

extra:
  recipe-maintainers:
    - pmlandwehr
    - dgasmith
    - lnaden
