{% set name = "mongoengine" %}
{% set version = "0.28.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "67c35a2ebe0ee7fd8eda3766dc251b9e0aada4489bb935f7a55b4c570d148ca7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip

  run:
    - python
    - pymongo >=2.7.1

test:
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: MongoEngine is a Python Object-Document Mapper for working with MongoDB.
  doc_url: https://mongoengine-odm.readthedocs.io/
  dev_url: https://github.com/MongoEngine/mongoengine

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
