{% set name = "mongoengine" %}
{% set version = "0.29.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "3b43abaf2d5f0b7d39efc2b7d9e78f4d4a5dc7ce92b9889ba81a5a9b8dee3cf3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pymongo >=3.4,<5.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mongoengine
    - mongoengine.base
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: MongoEngine is a Python Object-Document Mapper for working with MongoDB.
  doc_url: https://mongoengine-odm.readthedocs.io/
  dev_url: https://github.com/MongoEngine/mongoengine

extra:
  recipe-maintainers:
    - dgasmith
    - lnaden
